//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace chapter_2._9
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EF6Recipes9 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EF6Recipes9 object using the connection string found in the 'EF6Recipes9' section of the application configuration file.
        /// </summary>
        public EF6Recipes9() : base("name=EF6Recipes9", "EF6Recipes9")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EF6Recipes9 object.
        /// </summary>
        public EF6Recipes9(string connectionString) : base(connectionString, "EF6Recipes9")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EF6Recipes9 object.
        /// </summary>
        public EF6Recipes9(EntityConnection connection) : base(connection, "EF6Recipes9")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }

        #endregion

    }

    #endregion

    //#region Entities
    
    ///// <summary>
    ///// No Metadata Documentation available.
    ///// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="EF6Recipes9Model", Name="Account")]
    //[Serializable()]
    //[DataContractAttribute(IsReference=true)]
    //public partial class Account : EntityObject
    //{
    //    #region Factory Method
    
    //    /// <summary>
    //    /// Create a new Account object.
    //    /// </summary>
    //    /// <param name="accountID">Initial value of the AccountID property.</param>
    //    public static Account CreateAccount(global::System.Int32 accountID)
    //    {
    //        Account account = new Account();
    //        account.AccountID = accountID;
    //        return account;
    //    }

    //    #endregion

    //    #region Primitive Properties
    
    //    /// <summary>
    //    /// No Metadata Documentation available.
    //    /// </summary>
    //    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    //    [DataMemberAttribute()]
    //    public global::System.Int32 AccountID
    //    {
    //        get
    //        {
    //            return _AccountID;
    //        }
    //        set
    //        {
    //            if (_AccountID != value)
    //            {
    //                OnAccountIDChanging(value);
    //                ReportPropertyChanging("AccountID");
    //                _AccountID = StructuralObject.SetValidValue(value);
    //                ReportPropertyChanged("AccountID");
    //                OnAccountIDChanged();
    //            }
    //        }
    //    }
    //    private global::System.Int32 _AccountID;
    //    partial void OnAccountIDChanging(global::System.Int32 value);
    //    partial void OnAccountIDChanged();
    
    //    /// <summary>
    //    /// No Metadata Documentation available.
    //    /// </summary>
    //    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    //    [DataMemberAttribute()]
    //    public Nullable<global::System.Int32> AccountHolderID
    //    {
    //        get
    //        {
    //            return _AccountHolderID;
    //        }
    //        set
    //        {
    //            OnAccountHolderIDChanging(value);
    //            ReportPropertyChanging("AccountHolderID");
    //            _AccountHolderID = StructuralObject.SetValidValue(value);
    //            ReportPropertyChanged("AccountHolderID");
    //            OnAccountHolderIDChanged();
    //        }
    //    }
    //    private Nullable<global::System.Int32> _AccountHolderID;
    //    partial void OnAccountHolderIDChanging(Nullable<global::System.Int32> value);
    //    partial void OnAccountHolderIDChanged();

    //    #endregion

    
    //}

    //#endregion

    
}
